# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-10 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedHabitationElementsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('f_l', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('as_l', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fe_l', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('n_l', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('s_l', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('f_al', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('as_al', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fe_al', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('n_al', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('s_al', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('f_count', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fe_count', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('as_count', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('n_count', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('s_count', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created', models.DateField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=2000)),
                ('data', jsonfield.fields.JSONField()),
                ('status', models.IntegerField()),
                ('habitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.HabitationData')),
            ],
        ),
    ]
