# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=2000)),
                ('data', jsonfield.fields.JSONField()),
                ('status', models.IntegerField()),
                ('habitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.HabitationData')),
            ],
        ),
    ]
