KEY_SUCCESS="success"
KEY_MESSAGE="message"

KEY_VERSION="version"
KEY_COMPULSORY_UPDATE="compulsory_update"

KEY_FCM="fcm"
KEY_ACCESS_TOKEN = "access_token"
KEY_TEMP_ACCESS_TOKEN="temp_access_token"

KEY_MOBILE = "mobile"
KEY_OTP = "otp"
KEY_PASSWORD = "password"

KEY_WELCOME_PAGE="welcome_page"
KEY_ID="id"
KEY_IMAGE_URL="image_url"

KEY_COLLEGE_LIST="college_list"

KEY_NAME="name"
KEY_EMAIL="email"
KEY_COLLEGE_NAME="college_name"
KEY_RANK="rank"

KEY_TAB_LIST='tab_list'
KEY_TAB_TITLE='title'
KEY_TAB_POSITION='position'
KEY_TAB_ID='id'

KEY_STORY="story"
KEY_STORY_IMAGE="image_url"

KEY_NEXT_QUESTION='next_question'
KEY_QUESTION='question'
KEY_QUESTION_NAME='question_name'
KEY_QUESTION_NO='question_no'
KEY_QUESTION_CONTENT='question_content'
KEY_QUESTION_IMAGE='question_img'
KEY_QUESTION_ANSWER='answer'
KEY_SOLVED_QUESTION_LIST='solved_question_list'
KEY_QUESTION_HINTS='hint'
KEY_HINT_LIST='hint_list'

KEY_ANSWERED='answered'


KEY_ABOUT_US='text'
KEY_SPONSOR_NAME="name"
KEY_SPONSOR_CONTENT="content"
KEY_SPONSOR_IMAGE="image_url"
KEY_SPONSOR_URL="web_url"

KEY_SPONSOR_LIST="sponserDetails"


KEY_ACCESS_TOKEN_ENCRYPTION="1728123"
KEY_PASSWORD_ENCRYPTION = "123123"
KEY_TEMP_ACCESS_TOKEN_ENCRYPTION = "123123"


KEY_SENDER_ID="MKLEOS"
KEY_MSG91="12312312312312312312312"
KEY_DEFAULT_PASSWORD="12312312312312312"