# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-10 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='DistrictData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ElementData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hazards', models.CharField(blank=True, max_length=1500, null=True)),
                ('remedy', models.CharField(blank=True, max_length=1500, null=True)),
                ('permissible_limit_low', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('permissible_limit_high', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='HabitationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('latitude', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='HabitationElementData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created', models.DateField()),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.ElementData')),
                ('habitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.HabitationData')),
            ],
        ),
        migrations.CreateModel(
            name='Officials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('department', models.CharField(max_length=254)),
                ('designation', models.CharField(max_length=254)),
                ('location', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=11)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.BlockData')),
            ],
        ),
        migrations.CreateModel(
            name='PanchayatData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.BlockData')),
            ],
        ),
        migrations.CreateModel(
            name='StateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='VillageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('panchayat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.PanchayatData')),
            ],
        ),
        migrations.AddField(
            model_name='habitationdata',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.VillageData'),
        ),
        migrations.AddField(
            model_name='districtdata',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.StateData'),
        ),
        migrations.AddField(
            model_name='blockdata',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.DistrictData'),
        ),
    ]
