# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedHabitationElementData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('alert_level', models.IntegerField(default=0)),
                ('f_al', models.IntegerField(default=0)),
                ('f_l', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('as_al', models.IntegerField(default=0)),
                ('as_l', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fe_al', models.IntegerField(default=0)),
                ('fe_l', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('n_al', models.IntegerField(default=0)),
                ('n_l', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('sl_al', models.IntegerField(default=0)),
                ('sl_l', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('address', models.CharField(max_length=2000)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
